# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
labels:
  org.opencontainers.image.title: "valetudopng homeassistant addon"
  org.opencontainers.image.description: "erkexzcx's excellent Valetudo map renderer (ex Hypfer/ICantBelieveItsNotValetudo) for Home Assistant."
  org.opencontainers.image.source: "https://github.com/ajaxbits/valetudopng-ha-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  VALETUDOPNG_VERSION: "1.0.17"
