# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ValetudoPNG
version: "1.0.14"
slug: valetudopng-addon
description: ValetudoPNG addon
url: "https://github.com/ajaxbits/valetudopng-ha-addon"
services:
  - mqtt:need
webui: http://[HOST]:[PORT:3000]/api/map/image/debug
arch:
  - aarch64
  - amd64
  - armv7
init: false
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: ValetudoPNG frontend port
map:
  - config:rw
options:
  data_path: "/config/valetudopng"
schema:
  data_path: "str"
image: "ghcr.io/ajaxbits/valetudopng"
